# Generated by Django 4.2.15 on 2024-11-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0002_destination_activity_alter_destination_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="activity",
            field=models.TextField(),
        ),
    ]
