# Generated by Django 4.2.15 on 2024-11-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="activity",
            field=models.TextField(default="无活动"),
        ),
        migrations.AlterModelTable(
            name="destination",
            table="destination",
        ),
    ]
