# Generated by Django 4.2.15 on 2024-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0003_alter_destination_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_name", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
                ("days", models.IntegerField()),
                ("start_date", models.DateField()),
            ],
            options={
                "db_table": "trip_information",
            },
        ),
        migrations.RenameField(
            model_name="destination",
            old_name="activity",
            new_name="tag",
        ),
    ]
