# Generated by Django 4.2.16 on 2024-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_tripplan_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinformation',
            name='weather_info',
            field=models.JSONField(default=dict, verbose_name='天气信息'),
        ),
    ]
