# Generated by Django 4.2.16 on 2024-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_tripinformation_weather_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='图片URL'),
        ),
    ]
