# Generated by Django 4.2.16 on 2024-11-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_tripplan_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripplan',
            old_name='trip_description',
            new_name='trip_destination',
        ),
    ]
