# Generated by Django 4.2.16 on 2024-11-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_rename_trip_description_tripplan_trip_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='经纬度'),
        ),
    ]
