# Generated by Django 5.1.3 on 2024-11-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='content',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='memo',
            name='status',
            field=models.CharField(choices=[('yes', '带了行李'), ('no', '没带行李')], default='no', max_length=3),
        ),
    ]
